version: '3.6'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    env_file: .env
#    environment:
#      VIRTUAL_HOST: ${MQTT_VIRTUAL_HOST}
#      VIRTUAL_PORT: 9001
#      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${MQTT_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9001:9001"
      - "1883:1883"
#    restart: unless-stopped
