version: '3.7'

networks:
  proxy_net:
    name: proxy_net
    external: true

services:
  webforms:
    image: brian32768/webforms:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: /srv
      FLASK_APP: start_app
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      VIRTUAL_HOST: webforms.co.clatsop.or.us
      VIRTUAL_PORT: 5000
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: webforms.co.clatsop.or.us
      LETSENCRYPT_MAIL: ${MY_EMAIL}
      PORTAL_URL: ${PORTAL_URL}
    command: ["flask", "run"]
    volumes:
      - .:/srv
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

      # This allows writing updated CSV files directly into the nginx "capacity" docker
      # from the csv_export.py script.
      - "/home/gis/docker/capacity/html/cases:/srv/cases:rw"
    user: app
    networks:
      proxy_net:
        aliases:
          - webforms
    # proxy will not work without this
    ports:
      - "5000:5000"
    # for docker-compose
    restart: unless-stopped
    # Swarm deployment, which does not work yet
    #deploy:
    #  mode: global
    #  restart_policy:
    #    condition: any
    #    delay: 5s
    #    window: 15s
    #    max_attempts: 10

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
